name: cs599-dl-lab4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - black
  - isort
  - numpy=1.24.3
  - matplotlib
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - requests
  - tqdm
  - dask
  - dask-jobqueue
  - distributed
  - pip
  - pip:
    - tensorflow>=2.12.0,<2.13.0