name: cs599-dl-lab4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - black
  - isort
  - numpy=1.24.3  # Specify a specific version of NumPy 1.x
  - matplotlib
  - scikit-learn=1.2.2  # Compatible with NumPy 1.x
  - scipy=1.10.1  # Compatible with NumPy 1.x
  - pip
  - pip:
    - tensorflow>=2.12.0,<2.13.0  # Specify a compatible TensorFlow version